server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoni2009/spring-cloud-config-repo.git     # 配置Git仓库的地址
          username:                                                         # Git仓库的账号
          password:                                                         # Git仓库的密码
        health:
          # 禁用监控状况指示器，如果禁用，不管访问repositories是否存在，访问localhost:8080/health显示的结果一直都是{"status": "UP"}
#          enabled: false
          repositories:
            # 默认健康检查的是EnvironmentRepository对应的{application} {profile} {label}的端点，可通过如下配置修改监控检查的端点
            # 配置多个，访问localhost:8080/health显示所有的repo的配置文件状态的交集，即有一个repo不存在，则返回down。
            # 存在的 显示
            # {
            #    "status": "UP"
            #}
            # 不存在的显示
            # {
            #    "status": "DOWN"
            #}
            # 存在的
            a-foo:
              label: cofig-label-v2.0
              name: microservice-foo
              profiles: dev
            # 不存在的，注释掉后，则返回结果是up
            c-foo:
              label: abc
              name: microservice-foo
              profiles: dev
            # 存在的
            b-foo:
              label: master
              name: microservice-foo
              profiles: dev
