server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaoni2009/spring-cloud-config-repo.git      # 配置Git仓库的地址
          username:                                                        # Git仓库的账号
          password:                                                     # Git仓库的密码

security:
  basic:
    enabled: true #开启基于HTTP basic的认证
  user:
    name: user #配置登陆的账号，默认是user
    password: password123 #配置登陆的密码，默认是随机密码，项目启动时会打印出来