server:
  port: 8761

eureka:
  client:
    # 是否将自己注册到eureka,默认是true
    register-with-eureka: false
    # 是否从eureka server获取注册信息，默认为true。因为当前应用就是eureka server，所以设置成false
    fetch-registry: false
    serviceUrl:
      # 设置与eureka server交互的地址，查询服务和注册服务都需要依赖这个地址。多个地址间，用","分隔
      defaultZone: http://localhost:8761/eureka/